client_config_backend: settings
client_config:
    client_id: 871367448067-99duhnj4afaakvt81a2p9vj44i5875ar.apps.googleusercontent.com
    client_secret: typWbb5x-HTzQqiV1LHjYkWE

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install