client_config_backend: settings
client_config:
  client_id: 871367448067-3dli2sde4amkeqg2nrcij38kqls285o2.apps.googleusercontent.com
  client_secret: m8XXcDH2pYNVHWHCQL6_YAi5

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install 